// function that loads contact page

function loadContact(){
    let divs = document.querySelectorAll('div');
    let images = document.querySelectorAll('img');
    images.forEach(image => image.remove());
    for(let n = 1; n < divs.length; n++){
        divs[n].remove();
    };
    let content = document.querySelector('#content');
        let header = document.createElement('div');
        header.classList.add('header');
        content.appendChild(header);
            let logo = document.createElement('div');
            logo.classList.add('logo');
            header.appendChild(logo);
                let mango = document.createElement('img');
                mango.src = '../images/mango.png';
                mango.width = '125';
                logo.appendChild(mango);
                let organics = document.createElement('h1');
                organics.textContent = 'ORGANICS';
                logo.appendChild(organics);
            let links = document.createElement('ul');
            links.classList.add('links');
            header.appendChild(links);
                let menu = document.createElement('li');
                menu.textContent = 'Menu';
                links.appendChild(menu);
                let about = document.createElement('li');
                about.textContent = 'About';
                links.appendChild(about);
                let contact = document.createElement('li');
                contact.textContent = 'Contact';
                links.appendChild(contact);
        let body2 = document.createElement('div');
        body2.classList.add('body2');
        content.appendChild(body2);
            let nameLabel = document.createElement('label');
            nameLabel.htmlFor = 'name';
            nameLabel.textContent = 'Name';
            body2.appendChild(nameLabel);
            let nameInput = document.createElement('input');
            nameInput.type = 'text';
            nameInput.id = 'name';
            nameInput.name = 'name';
            body2.appendChild(nameInput);
            let emailLabel = document.createElement('label');
            emailLabel.htmlFor = 'email';
            emailLabel.textContent = 'Email';
            body2.appendChild(emailLabel);
            let emailInput = document.createElement('input');
            emailInput.type = 'text';
            emailInput.id = 'email';
            emailInput.name = 'email';
            body2.appendChild(emailInput);
            let messageLabel = document.createElement('label');
            messageLabel.htmlFor = 'message';
            messageLabel.textContent = 'Message';
            body2.appendChild(messageLabel);
            let messageInput = document.createElement('textarea');
            messageInput.id = 'message';
            messageInput.name = 'message';
            body2.appendChild(messageInput);
            let submitButton = document.createElement('button');
            submitButton.type = 'button';
            submitButton.textContent = 'Submit';
            body2.appendChild(submitButton);
};

export { loadContact };